/**
 * Fetches the OpenAPI spec from the Chatterbox TTS API and generates TypeScript types.
 *
 * Usage:
 *   CHATTERBOX_API_URL=https://your-api-url npm run sync-api
 *
 * Or with .env file:
 *   npm run sync-api
 *
 * ¿Qué problema resuelve?
 * Modal expone el modelo TTS como una API HTTP. TypeScript no sabe qué forma
 * tienen los datos que entran y salen de esa API. Sin tipos, trabajas a ciegas
 * y pierdes todo el autocompletado y seguridad de tipos.
 *
 * ¿Qué hace este script?
 * 1. Se conecta al endpoint de Modal y descarga el esquema OpenAPI (/openapi.json)
 *    — un documento JSON que describe todos los endpoints, parámetros y respuestas.
 * 2. Convierte ese esquema en tipos TypeScript automáticamente.
 * 3. Los guarda en src/types/chatterbox-api.d.ts
 *
 * ¿Cuándo ejecutarlo?
 * Solo cuando la API de Modal cambie — si se añaden parámetros nuevos, cambia
 * el formato de respuesta, etc. No es algo que corras constantemente, sino
 * únicamente cuando haya cambios en el backend Python.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";                                          // Utilidad para convertir la URL del archivo actual en una ruta de directorio
import "dotenv/config";
// openapiTS: convierte un esquema OpenAPI (JSON) en tipos TypeScript
// astToString: convierte el resultado (un AST) en texto TypeScript legible
import openapiTS, { astToString } from "openapi-typescript";



const __dirname = path.dirname(fileURLToPath(import.meta.url));                    // En módulos ES, __dirname no existe por defecto — esto lo reconstruye
const OUTPUT_PATH = path.resolve(__dirname, "../src/types/chatterbox-api.d.ts");   // Ruta donde se guardará el archivo de tipos generado automáticamente

async function main() {
  const apiUrl = process.env.CHATTERBOX_API_URL;                                   // Lee la URL del endpoint de Modal desde las variables de entorno
  if (!apiUrl) {
    console.error("Error: CHATTERBOX_API_URL environment variable is required");
    process.exit(1);
  }

  // Modal expone automáticamente el esquema OpenAPI en la ruta /openapi.json
  // Ese esquema describe todos los endpoints, parámetros y tipos de respuesta
  const openApiUrl = `${apiUrl}/openapi.json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

  const ast = await openapiTS(new URL(openApiUrl));                                // Descarga el esquema y lo convierte en un AST (árbol sintáctico de TypeScript)
  const contents = astToString(ast);                                               // Convierte el AST en texto TypeScript plano que se puede escribir en un archivo
  const outputDir = path.dirname(OUTPUT_PATH);                                     // Crea el directorio de destino si no existe todavía 
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Cabecera que se añade al archivo generado para advertir que no debe editarse a mano
  const header = `/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated from: ${openApiUrl}
* Generated at: ${new Date().toISOString()}
*/
  `;
  fs.writeFileSync(OUTPUT_PATH, header + contents);                                // Escribe el archivo final: cabecera + tipos generados
  console.log(`Types written to: ${OUTPUT_PATH}`);
}

main().catch((err) => {                                                            // Ejecuta la función principal y captura cualquier error inesperado
  console.error("Failed to sync API types:", err);
  process.exit(1);
});